### ISSUE TITLE
Usage help should be displayed when no options are given

### ISSUE THREAD

**Issue by lusocoding** [TeamYARM/YARM-CLI#2]
When the option -i is not passed to the CLI an unhanded exception is being thrown instead of gracefully die and output usage help. Same happens when no options are passed at all.

![Unhandled exception when input file is not given to CLI](https://user-images.githubusercontent.com/114126/58419822-8a3f8300-8083-11e9-98fa-1ce0eb3404e2.png)

**Comment by justinyoo** [comment]
@lusocoding Thanks for your PR. Yours has been merged and released as 0.3.1:

[https://github.com/TeamYARM/YARM-CLI/releases/tag/yarm-cli-v0.3.1](https://github.com/TeamYARM/YARM-CLI/releases/tag/yarm-cli-v0.3.1)
